name: Build RSDKv3 Win64 and Android Unlocked

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  GENERAL_FLAGS: "-DRETRO_DISABLE_PLUS=OFF -DCMAKE_BUILD_TYPE=Release"
  GENERAL_WIN_FLAGS: "-DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake"
  WIN64_FLAGS: "-DVCPKG_TARGET_TRIPLET=x64-windows-static -DCMAKE_PREFIX_PATH=C:/vcpkg/installed/x64-windows-static/"

jobs:
  v3-windows-x64:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: vcpkg install glew sdl2 libogg libtheora libvorbis --triplet=x64-windows-static

      - name: Build RSDKv3
        run: |
          cmake -B build ${{env.GENERAL_FLAGS}} ${{env.GENERAL_WIN_FLAGS}} ${{env.WIN64_FLAGS}}
          cmake --build build --parallel --config Release

      - name: Move artifacts
        run: |
          mkdir artifacts
          mv ./build/Release/*.exe ./artifacts

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SonicCD-Win64-Unlocked
          path: artifacts

  v3-android:
    runs-on: windows-latest
    steps:
      - name: Checkout repository Android
        uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
        
      - name: Download libogg, libvorbis, and libtheora for easier includes
        run: |
          Invoke-WebRequest -Uri "https://osuosl.org" -OutFile "libvorbis.zip"
          Expand-Archive -Path libvorbis.zip -DestinationPath ./dependencies/android/
          Rename-Item ./dependencies/android/libvorbis-1.3.7 libvorbis
          Invoke-WebRequest -Uri "https://osuosl.org" -OutFile "libogg.zip"
          Expand-Archive -Path libogg.zip -DestinationPath ./dependencies/android/app/jni/src/dependencies/android/
          Rename-Item ./dependencies/android/app/jni/src/dependencies/android/libogg-1.3.5 libogg
          Invoke-WebRequest -Uri "https://osuosl.org" -OutFile "libtheora.zip"
          Expand-Archive -Path libtheora.zip -DestinationPath ./dependencies/android
          Rename-Item ./dependencies/android/libtheora-1.1.1 libtheora
          
      - name: Download GLEW
        run: |
          Invoke-WebRequest -Uri "https://github.com" -OutFile "GLEW.zip"
          Expand-Archive -Path GLEW.zip -DestinationPath ./dependencies/android/
          Rename-Item ./dependencies/android/glew-2.2.0 glew
          
      - name: Download SDL2
        run: |
          Invoke-WebRequest -Uri "https://libsdl.org" -OutFile "SDL2.zip"
          Expand-Archive -Path SDL2.zip -DestinationPath ./android/app/jni/
          Rename-Item ./android/app/jni/SDL2-2.28.3 SDL
          
      - name: Move & Copy stuff
        run: |
          Copy-Item -Path ./dependencies/all/theoraplay -Destination ./dependencies/android/app/jni/src/dependencies/android/
          Copy-Item -Path ./dependencies/android/app/jni/src/dependencies/android/* -Destination ./dependencies/
          Copy-Item -Path ./dependencies/android/app/jni/src/dependencies/android/libogg/ -Destination ./dependencies/android/ -recurse
          Copy-Item -Path ./dependencies/android/config_types.h -Destination ./dependencies/android/libogg/include/ogg/
          
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 11
          
      - name: Build RSDKv3 Android
        working-directory: ./android
        run: |
          ./gradlew.bat assembleDebug --no-daemon -PABIFILTERS="armeabi-v7a;arm64-v8a"
          
      - name: Upload artifact Android
        uses: actions/upload-artifact@v4
        with:
          name: SonicCD-Android-Unlocked
          path: ./android/app/build/outputs/apk
